name: pysv_website
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - lektor=3.2
  - ca-certificates
  - certifi
  - openssl
  - jinja2=3.1
  - pip=21
  - pip:
    - python-avatars==1.3