name: Upload  Staging Website

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Message Checkout
      run: echo Checking out repository
      
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy static site to staging S3 bucket
      run: |
        echo Installing requirements
        pip install -r requirements_deploy.txt
        cd website
        lektor project-info
        echo Building website
        lektor build --output-path ./www
        echo Built website, syncing to s3 now
        aws s3 sync ./www s3://pysv-web-staging --delete
        echo DONE
