name: Upload  Staging Website

on:
  pull_request:
    paths:
      - 'website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy static site to staging S3 bucket
      run: |
        pip install -r requirements_deploy.txt
        cd website
        lektor project-info
        lektor build --output-path ./www
        aws s3 sync ./www s3://pysv-web-staging --delete
